version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: springfoyer
    ports:
      - "3306:3306"
    networks:
      - backend

  springfoyer:
    build: .
    container_name: springfoyer
    restart: always
    depends_on:
      - mysql
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/springfoyer
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
      SERVER_PORT: 8081  # Ajout explicite
    networks:
      - backend

networks:
  backend:
