apiVersion: v1
kind: Service
metadata:
  name: springfoyer-service
spec:
  type: NodePort
  selector:
    app: springfoyer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080   # accessible via 10.0.4.4:30080
